- name: Combine additional pull secrets
  delegate_to: localhost
  run_once: true
  ansible.builtin.set_fact:
    ocp4_deployment_cluster_pull_secrets_combined:
      auths: "{{
          (ocp4_deployment_cluster_pull_secret | from_json).auths | combine(
            ocp4_deployment_cluster_pull_secrets_combined.auths | d({}) | combine({
              item.hostname: {
                'auth': (item.username + ':' + item.password) | b64encode,
                'email': item.email | d('none@example.com')
              }
            })
          )
        }}"
  loop: "{{ ocp4_deployment_cluster_additional_pull_secrets | d([]) }}"

- name: Configure Global Pull Secret
  delegate_to: localhost
  run_once: true
  when: ocp4_deployment_cluster_configure_pull_secret | bool
  kubernetes.core.k8s:
    kind: Secret
    name: pull-secret
    namespace: openshift-config
    definition:
      data:
        '.dockerconfigjson': "{{ ocp4_deployment_cluster_pull_secrets_combined | d(ocp4_deployment_cluster_pull_secret | from_json) | to_json | b64encode }}"

# code: language=ansible
