- name: Install ElasticSearch Operator
  ansible.builtin.include_tasks:
    file: _install-operator.yml
    apply:
      vars:
        _ocp4_deployment_operator_name: elasticsearch-operator
        _ocp4_deployment_operator_namespace: openshift-operators-redhat
        _ocp4_deployment_operator_all_namespaces: true
        _ocp4_deployment_operator_channel: "{{ ocp4_deployment_cluster_logging_version }}"
        _ocp4_deployment_operator_source: redhat-operators
        _ocp4_deployment_operator_sourcenamespace: openshift-marketplace

- name: Install Logging Operator
  ansible.builtin.include_tasks:
    file: _install-operator.yml
    apply:
      vars:
        _ocp4_deployment_operator_name: cluster-logging
        _ocp4_deployment_operator_namespace: openshift-logging
        _ocp4_deployment_operator_channel: "{{ ocp4_deployment_cluster_logging_version }}"
        _ocp4_deployment_operator_source: redhat-operators
        _ocp4_deployment_operator_sourcenamespace: openshift-marketplace
        _ocp4_deployment_operator_enable_consoleplugin: logging-view-plugin

- name: Configure Logging
  delegate_to: localhost
  run_once: true
  kubernetes.core.k8s:
    kind: ClusterLogging
    api_version: logging.openshift.io/v1
    name: instance
    namespace: openshift-logging
    template: logging-conf.j2

- name: Configure ClusterLogForwarding
  delegate_to: localhost
  run_once: true
  when: ocp4_deployment_cluster_logging_forwarding_spec is defined
  kubernetes.core.k8s:
    kind: ClusterLogForwarding
    api_version: logging.openshift.io/v1
    name: instance
    namespace: openshift-logging
    definition:
      spec: "{{ ocp4_deployment_cluster_logging_forwarding_spec }}"

# code: language=ansible
