- name: Make List of Storage Nodes
  run_once: true
  ansible.builtin.set_fact:
    _ocp4_deployment_configure_storage_node_list: "{{ _ocp4_deployment_configure_storage_node_list | d([]) + [ hostvars[item].inventory_hostname ] }}"
  when: '"cluster.ocs.openshift.io/openshift-storage" in hostvars[item].ocp4_deployment_cluster_nodes_labels | d({})'
  loop: "{{ ansible_play_hosts }}"

- name: Install ODF Operator
  ansible.builtin.include_tasks:
    file: install-operator.yml
    apply:
      vars:
        _ocp4_deployment_operator_name: odf-operator
        _ocp4_deployment_operator_namespace: openshift-storage
        _ocp4_deployment_operator_channel: "{{ ocp4_deployment_cluster_odf_version }}"
        _ocp4_deployment_operator_source: redhat-operators
        _ocp4_deployment_operator_sourcenamespace: openshift-marketplace
        _ocp4_deployment_operator_enable_consoleplugin: odf-console

- name: Configure CSI Plugin Tolerations
  delegate_to: localhost
  run_once: true
  kubernetes.core.k8s:
    kind: ConfigMap
    name: rook-ceph-operator-config
    namespace: openshift-storage
    definition: "{{ lookup('template', 'rook-ceph-operator-config.j2') }}"

- name: If LocalStorage is being used
  when: ocp4_deployment_cluster_odf_use_localstorage | bool
  block:

    - name: Install LocalStorage Operator
      ansible.builtin.include_tasks:
        file: install-operator.yml
        apply:
          vars:
            _ocp4_deployment_operator_name: local-storage-operator
            _ocp4_deployment_operator_namespace: openshift-local-storage
            _ocp4_deployment_operator_channel: stable
            _ocp4_deployment_operator_source: redhat-operators
            _ocp4_deployment_operator_sourcenamespace: openshift-marketplace

    - name: Create LocalVolumeDiscovery
      delegate_to: localhost
      run_once: true
      kubernetes.core.k8s:
        kind: LocalVolumeDiscovery
        api_version: local.storage.openshift.io/v1alpha1
        name: auto-discover-devices
        namespace: openshift-local-storage
        definition:
          spec:
            tolerations:
              - effect: NoSchedule
                operator: Equal
                key: node.ocs.openshift.io/storage
                value: 'true'
            nodeSelector:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values: "{{ _ocp4_deployment_configure_storage_node_list }}"

    - name: Wait for Local Volume Discovery to Complete
      delegate_to: localhost
      run_once: true
      kubernetes.core.k8s_info:
        kind: LocalVolumeDiscoveryResult
        api_version: local.storage.openshift.io/v1alpha1
        namespace: openshift-local-storage
      register: _ocp4_deployment_configure_localvolumediscovery_info
      retries: 30
      delay: 5
      until: |
        _ocp4_deployment_configure_storage_node_list |
        difference(
          _ocp4_deployment_configure_localvolumediscovery_info.resources |
          map(attribute='spec.nodeName')
        ) | length == 0

    - name: Create LocalVolumeSet
      delegate_to: localhost
      run_once: true
      kubernetes.core.k8s:
        api_version: local.storage.openshift.io/v1alpha1
        kind: LocalVolumeSet
        name: localblock-odf-1
        namespace: openshift-local-storage
        definition:
          spec:
            tolerations:
              - effect: NoSchedule
                operator: Equal
                key: node.ocs.openshift.io/storage
                value: 'true'
            nodeSelector:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: cluster.ocs.openshift.io/openshift-storage
                      operator: Exists
            storageClassName: localblock-odf
            volumeMode: Block
            deviceInclusionSpec:
              deviceTypes:
                - disk
              minSize: 100Gi
              maxSize: 100Ti

    - name: Create Storage Cluster with Local Storage
      delegate_to: localhost
      run_once: true
      when: ocp4_deployment_cluster_odf_use_localstorage | bool
      kubernetes.core.k8s:
        kind: List
        namespace: openshift-storage
        definition: "{{ lookup('template', 'storagecluster-localstorage.j2') }}"

- name: Create Storage Cluster with Dynamic Provisioning
  delegate_to: localhost
  run_once: true
  when: not ocp4_deployment_cluster_odf_use_localstorage | bool
  kubernetes.core.k8s:
    kind: List
    namespace: openshift-storage
    definition: "{{ lookup('template', 'storagecluster-dynprov.j2') }}"

- name: Wait for StorageCluster to Complete
  delegate_to: localhost
  run_once: true
  kubernetes.core.k8s_info:
    kind: StorageCluster
    api_version: ocs.openshift.io/v1
    name: ocs-storagecluster
    namespace: openshift-storage
  register: _ocp4_deployment_configure_storagecluster_info
  retries: 30
  delay: 60
  until: _ocp4_deployment_configure_storagecluster_info.resources[0].status.phase | d('') == "Ready"

# code: language=ansible
