- name: Create additional objects # noqa: args[module]
  delegate_to: localhost
  run_once: true
  kubernetes.core.k8s: "{{ manifest }}"
  loop: "{{ ocp4_deployment_cluster_additional_manifests }}"
  loop_control:
    loop_var: manifest

# code: language=ansible
