- name: Disable Self-Provisioning permission
  delegate_to: localhost
  run_once: true
  kubernetes.core.k8s:
    kind: ClusterRoleBinding
    name: self-provisioners
    definition: "{{ lookup('file', 'self-provisioners.yml') | from_yaml }}"

# code: language=ansible
