- name: Disable Self-Provisioning permission
  delegate_to: localhost
  run_once: true
  kubernetes.core.k8s:
    kind: ClusterRoleBinding
    name: self-provisioners
    src: self-provisioners.yml

# code: language=ansible
