- name: "Install Operator : {{ _ocp4_additional_operator.operator_name }}"
  ansible.builtin.include_tasks:
    file: _install-operator.yml
    apply:
      vars:
        _ocp4_deployment_operator_name: "{{ _ocp4_additional_operator.operator_name }}"
        _ocp4_deployment_operator_namespace: "{{ _ocp4_additional_operator.operator_namespace }}"
        _ocp4_deployment_operator_channel: "{{ _ocp4_additional_operator.operator_channel }}"
        _ocp4_deployment_operator_source: "{{ _ocp4_additional_operator.operator_source }}"
        _ocp4_deployment_operator_sourcenamespace: "{{ _ocp4_additional_operator.operator_sourcenamespace }}"
        _ocp4_deployment_operator_all_namespaces: "{{ _ocp4_additional_operator.operator_all_namespaces | d(false) }}"
        _ocp4_deployment_operator_enable_consoleplugin: "{{ _ocp4_additional_operator.operator_enable_consoleplugin | d('') }}"
  loop: "{{ ocp4_deployment_cluster_additional_operators }}"
  loop_control:
    loop_var: _ocp4_additional_operator
