- name: Delete Machines
  delegate_to: localhost
  community.vmware.vmware_guest:
    hostname: "{{ ocp4_deployment_vmware_vcenter_hostname }}"
    username: "{{ ocp4_deployment_vmware_vcenter_username }}"
    password: "{{ ocp4_deployment_vmware_vcenter_password }}"
    validate_certs: false
    name: "{{ inventory_hostname }}"
    state: absent
    force: true
    delete_from_inventory: true
  register: _ocp4_deployment_nodes_cleanup
  retries: 5
  delay: 10
  until: _ocp4_deployment_nodes_cleanup is success

# code: language=ansible
