- name: Remove All OCP VMs
  hosts:
    - bootstrap
    - master_nodes
    - worker_nodes
    - infra_nodes
    - storage_nodes
  become: false
  gather_facts: false
  vars:
    __ocp4_deployment_cleanup_pause_seconds: "{{ ocp4_deployment_cleanup_pause_seconds | d(60) }}"
    __ocp4_deployment_install_path: "{{ ocp4_deployment_install_path | d('/ocp4-deployment/') }}"
    __ocp4_deployment_cluster_rhcos_version: "{{ ocp4_deployment_cluster_version | split('.') | slice(2) | first | join('.') }}"
  tasks:
    - name: List all machines to be deleted
      ansible.builtin.debug:
        msg: "{{ ocp4_deployment_nodes_fqdn | d(inventory_hostname) }}"

    - name: Wait for confirmation
      ansible.builtin.pause:
        seconds: "{{ __ocp4_deployment_cleanup_pause_seconds }}"
        prompt: "Are you sure you want to delete the OCP cluster VMs? You have {{ __ocp4_deployment_cleanup_pause_seconds }} seconds to cancel."

    - name: Delete vmware VMs
      ansible.builtin.include_role:
        name: fcarrus.ocp4_deployment.deploy_vmware
        tasks_from: cleanup.yml
      when: ocp4_deployment_platform_provider == 'vmware'

# code: language=ansible
