- name: Post-deploy configuration
  hosts:
    - master_nodes
    - worker_nodes
    - infra_nodes
    - storage_nodes
  become: false
  gather_facts: false
  vars:
    __ocp4_deployment_install_path: "{{ ocp4_deployment_install_path | d('/ocp4-deployment/') }}"
    __ocp4_deployment_cluster_rhcos_version: "{{ ocp4_deployment_cluster_version | split('.') | slice(2) | first | join('.') }}"
  tasks:
    - name: Configure Cluster
      ansible.builtin.include_role:
        name: fcarrus.ocp4_deployment.configure
        apply:
          environment:
            K8S_AUTH_KUBECONFIG: "{{ __ocp4_deployment_install_path }}/install/auth/kubeconfig"
      tags:
        - always

# code: language=ansible
