- name: Remove install Directory
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    __ocp4_deployment_cleanup_pause_seconds: "{{ ocp4_deployment_cleanup_pause_seconds | d(60) }}"
    __ocp4_deployment_install_path: "{{ ocp4_deployment_install_path | d('/ocp4-deployment/') }}"
    __ocp4_deployment_cluster_rhcos_version: "{{ ocp4_deployment_cluster_version | split('.') | slice(2) | first | join('.') }}"
  tasks:
    - name: Wait for confirmation
      ansible.builtin.pause:
        seconds: "{{ __ocp4_deployment_cleanup_pause_seconds }}"
        prompt: "Are you sure you want to delete the install directory? You have {{ __ocp4_deployment_cleanup_pause_seconds }} seconds to cancel."

    - name: Delete install directory and its contents
      ansible.builtin.file:
        path: "{{ __ocp4_deployment_install_path }}/install"
        state: absent
        force: true

# code: language=ansible
