- name: Deploy Cluster
  hosts:
    - bootstrap
    - master_nodes
    - worker_nodes
    - infra_nodes
    - storage_nodes
  become: false
  gather_facts: false
  vars:
    __ocp4_deployment_install_path: "{{ ocp4_deployment_install_path | d('/ocp4-deployment/') }}"
    __ocp4_deployment_cluster_rhcos_version: "{{ ocp4_deployment_cluster_version | split('.') | slice(2) | first | join('.') }}"
  tasks:
    - name: Check install directory exists
      delegate_to: localhost
      run_once: true
      ansible.builtin.stat:
        path: "{{ __ocp4_deployment_install_path }}/install"
      register: __ocp4_deployment_installdir_stat
    
    - name: Assert install directory exists
      run_once: true
      ansible.builtin.assert:
        that:
          - __ocp4_deployment_installdir_stat.stat.exists
        fail_msg: "Install directory does not exist. Please run the 'prepare' phase first."

    - name: Pre-Deploy VMware Tasks
      when: 
        - ocp4_deployment_is_upi | bool
        - ocp4_deployment_platform_provider == 'vmware'
      ansible.builtin.import_role:
        name: fcarrus.ocp4_deployment.deploy_vmware
        tasks_from: pre_deploy.yml

    - name: UPI Deployment
      when: ocp4_deployment_is_upi | bool
      block:

        - name: Deploy VMware VMs
          ansible.builtin.import_role:
            name: fcarrus.ocp4_deployment.deploy_vmware
            tasks_from: deploy.yml
          when: ocp4_deployment_platform_provider == 'vmware'

        - name: Wait for bootstrap to complete
          delegate_to: localhost
          run_once: true
          ansible.builtin.command:
            chdir: "{{ __ocp4_deployment_install_path }}"
            cmd: "{{ __ocp4_deployment_install_path }}/openshift-install wait-for bootstrap-complete --dir=./install"
          changed_when: false

        - name: Post-Deploy VMware Tasks
          ansible.builtin.import_role:
            name: fcarrus.ocp4_deployment.deploy_vmware
            tasks_from: post_deploy.yml
          when: ocp4_deployment_platform_provider == 'vmware'

        - name: Wait for installation to complete
          delegate_to: localhost
          run_once: true
          ansible.builtin.command:
            chdir: "{{ __ocp4_deployment_install_path }}"
            cmd: "{{ __ocp4_deployment_install_path }}/openshift-install wait-for install-complete --dir=./install"
          changed_when: false

    - name: IPI Deployment
      when: not ocp4_deployment_is_upi | bool
      block:

        - name: Create cluster
          delegate_to: localhost
          run_once: true
          ansible.builtin.command:
            chdir: "{{ __ocp4_deployment_install_path }}"
            cmd: "{{ __ocp4_deployment_install_path }}/openshift-install create cluster --dir=./install"
          changed_when: false

# code: language=ansible
