- name: Configure Bastion Environment
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - name: Configure Bastion Environment
      ansible.builtin.include_role:
        name: fcarrus.ocp4_deployment.prepare

# code: language=ansible
