- name: Configure Bastion Environment
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    __ocp4_deployment_install_path: "{{ ocp4_deployment_install_path | d('/ocp4-deployment/') }}"
    __ocp4_deployment_cluster_rhcos_version: "{{ ocp4_deployment_cluster_version | split('.') | slice(2) | first | join('.') }}"
  tasks:
    - name: Configure Bastion Environment
      ansible.builtin.include_role:
        name: fcarrus.ocp4_deployment.prepare

# code: language=ansible
